declare module "*.svg";
declare module "*.png";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.webp";
declare module "*.gif";
declare module "*.ico"
declare module "*.ttf"
declare module "*.woff"
declare module "*.woff2"
declare module "*.scss"
declare module "*.css"